### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by Techcable**
Started with the auto-generated "workflow" Github generated for me.

This will fix issue #294

Make sure to:

* [ ] Add an entry to CHANGELOG.md (if necessary)

### CODE REVIEW

**Comment by panicbit** [comment]
Please make sure that there is a test run with `--all-features` too (should be failing ATM).

**Comment by panicbit** [comment]
A run without default features is probably also a good idea.

**Comment by dpc** [comment]
Having a config option matrix or something would be best. I'm always worried when people submit PRs that they will break some non-trivial combination, but I don't have time to test them all manually.

**Comment by Techcable** [comment]
@dpc
> Having a config option matrix or something would be best. I'm always worried when people submit PRs that they will break some non-trivial combination, but I don't have time to test them all manually.

@panicbit
> Please make sure that there is a test run with --all-features too (should be failing ATM).

Yes. I'm working on all of this. I'm basing it around `rust-toolchain` and what some other crates are doing 😉  

Right now I'm planning to avoid using the `Makefile` and run cargo directly.

I'm also going to split `cargo check`, `cargo test` and `cargo clippy` run as independent jobs on three different versions: stable, nightly, and 1.27 (our MSRV).

For now, I think `cargo check` and `cargo test` will be required to succeed (with default features).

`cargo clippy` should always be optional (although we still want to run it).

Until we get things fixed, we need `cargo test` and `cargo check` with `--all-features` to be (temporarily) optional too.

**Comment by Techcable** [comment]
Okay so this *mostly* works, but it doesn't seem to understand that test failure is okay if using optional features (the `features != ""` test).

I'll work on this more later today

**Comment by Techcable** [comment]
Okay, this should be good to merge. The only actions that fail are tests when `features != default`

clippy & rustfmt are enabled, but they only give warnings, they never "fail".

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Pull request merged**
