### PR TITLE
Add support 2018-style macro imports

### LINKED ISSUE #178: Support 2018-style macro imports
[This example](https://docs.rs/slog/2.3.2/slog/#logging-to-the-terminal) from the crate-level docs, in 2018:

```ini
[dependencies]
slog = "2.3"
slog-async = "2.3"
slog-term = "2.4"
```

```rust
use slog::{o, Drain};

fn main() {
    let decorator = slog_term::TermDecorator::new().build();
    let drain = slog_term::FullFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();

    let _log = slog::Logger::root(drain, o!());
}
```

As of rustc 1.30.0-nightly (33b923fd4 2018-08-18) I receive the following error:

```console
error: cannot find macro `kv!` in this scope
 --> src/main.rs:8:42
  |
8 |     let _log = slog::Logger::root(drain, o!());
  |                                          ^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by ubnt-intrepid**
This PR is a modification of 9a14db2 to use built-in macros correctly in exposed macros.

Fixes #178.

### CODE REVIEW

**Comment by dpc** [comment]
Awesome!

How well tested this is? Do you see any way we could have it automatically tested? Could we add a 2018 crate that we compile from `.travis.yml` to make sure it keeps working etc.?

**Comment by ubnt-intrepid** [comment]
added a crate for testing 2018-style macro imports.

**Comment by ubnt-intrepid** [comment]
A concern is that it is necessary to import `__slog_builtin!()` when using old-style macro import, since the call of built-in macros will be replaced with it.
There is no effect on the general users (importing macros with just `#[macro_use]`), but if the users using explicitly macro import (like `#[macro_use(slog_o)]`) must add `__slog_builtin!()` to the import list.

**Comment by dpc** [comment]
So this is technically a breaking change? :(

Well, it's great work. I've added you to project collaborators. I'm having a second child, and looking for increasing the bus factor here. 

Maybe there would be a way to have an intermediate release that would  would warn users they have to import this new symbol?

If not, than I guess I'm fine with breakage. Or maybe we should do 3.0. Though the problem with that is it cascades all over the downstream. :/

**Comment by ubnt-intrepid** [comment]
It might be nervously thought about backward compatibility...

I've accepted the invitation to collaborators.  I'm looking forward to working with you :)
merging this pull request as the first job.

**Comment by pravic** [comment]
> So this is technically a breaking change? :(

Yes, it is and we've run into it already. 

It must have been mentioned somewhere (at least in release notes) in order to save time for those who are trying to find the culprit of the broken v2.4.0.

**Pull request merged**
